---
#- name: copy admin key to other hosts
#  copy:
#    src: /tmp/id_rsa.pub
#    dest: /tmp/id_rsa.pub
#    mode: 0644
- name: add admin key in authorized key
  authorized_key:
    user: cephadmin
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
