---
- name: Install a list of packages
  yum:
     name: "{{ packages }}"
     update_cache: yes
     state: latest

  vars:
    packages:
    - python
    - parted
    - chrony

- name: Copy a new "chrony.conf file into place, backing up the original if it differs from the copied version
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart chrony
