---
- name: Create .ssh directory
  file:
    path: /home/cephadmin/.ssh
    state: directory
    mode: 0755

- name: Generate SSH keys
  shell:
     ssh-keygen -b 2048 -f /home/cephadmin/.ssh/id_rsa -t rsa -q -N ""
  args:
    creates: /home/cephadmin/.ssh/id_rsa

- name: copy public key locally
  fetch:
    src: /home/cephadmin/.ssh/id_rsa.pub
    dest: /tmp/
    flat: yes

- name: copy ssh configuration
  copy:
    src: ssh_config
    dest: /home/cephadmin/.ssh/config
    mode: 0644

- name: empty known_hosts
  file:
    state: absent
    path: /home/cephadmin/.ssh/known_hosts

- name: run ssh-keyscan to add keys to known_hosts
  shell: "ssh-keyscan {{ item }} >> /home/cephadmin/.ssh/known_hosts"
  with_items:
    - "ceph-compute01"
    - "ceph-compute02"
    - "ceph-monitor"
