---
  - name: Change the hostname to our standard
    hostname:
      name: "{{ inventory_hostname_short }}"
    when: ansible_fqdn  !=  ansible_ssh_host 

  - name: Fix /etc/hosts removing the old hostname
    lineinfile:
      state: present
      path: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address }}"
      line: "{{ ansible_host  }}  {{ inventory_hostname_short }} {{ inventory_hostname }}"
